version: '3'
services:
  frontend:
    build:
      context: ./frontend
    expose:
      - "3000"
    volumes:
      - frontend-data:/app/data

  backend:
    build:
      context: ./backend
    expose:
      - "3001"
    volumes:
      - backend-data:/app/data

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  frontend-data:
  backend-data: